# ------------------------------------------------------------------    cli
HELP_DESCRIPTION = "This is a simple CLI based utility to create java/cpp enviroment projects"
EPILOG           = ""


# ---------------------------------------------------------------       gradle
GRADLE_ALL = [
    "basic",
    "cpp-application",
    "cpp-library",
    "groovy-application",
    "groovy-gradle-plugin",
    "java-application",
    "java-gradle-plugin",
    "java-library",
    "kotlin-application",
    "kotlin-gradle-plugin",
    "kotlin-library",
    "pom",
    "scala-application",
    "scala-library",
    "swift-application",
    "swift-library",
]

GRADLE_SCRIPT_LANG  = ["kotlin", "groovy"]


# -----------------------------------------------------------------     cmd
CMD_MKDIR_CONTENT   = ["mkdir", "-p"]
CMD_GRADLE_CONTENT  = ["gradle", "init", "--project-dir"]
CMD_REMOVER_PROJECT = ["rm", "-rf"]


# ---------------------------------------------------------------       files
START_FILE = f"""kitty --override initial_window_width=47c \
      --override initial_window_height=43c \
      >/dev/null 2>&1 &
"""

JAVA_STD_FILE = """package main;
/*
    This code is generated by this program
*/

public class Main
{
    public static void main(String[] argv)
    {
        // Code
    }
}"""

C_CPP_BOTTOM = """
int main(void)
{
    // code

    return 0;
}"""
