# globals
version_status = "1.0.2"

COMP_FILE_NAME = "build"
START_FILE_NAME = "start"
RIGHTS = "770" # rwx for user and group

MIN_ARGS = 2
MAX_ARGS = 4


STDO = "[\033[92m*\033[0m]: "
STDE = "[\033[91m!\033[0m]: "
STDI = "\033[92m>\033[0m "
ROOT_PATH = "/usr/local/lib/javaz"

opts = {
    "basic":    ["basic", "Creates empty gradle project"],
    
    "cppa":     ["cpp-application", "Creates C++ application"],
    "cppl":     ["cpp-library", "Creates C++ library"],
    
    "grva":     ["groovy-application", "Creates Groovy application"],
    "ggplug":   ["groovy-gradle-plugin", "Creates Groovy plugin"],
    
    "javaa":    ["java-application", "Creates Java application"],
    "javaplug": ["java-gradle-plugin", "Creates Java plugin"],
    "javal":    ["java-library", "Creates Java library"],

    "kota":     ["kotlin-application", "Creates Kotlin application",],
    "kotplug":  ["kotlin-gradle-plugin", "Creates Kotlin plugin"],
    "kotl":     ["kotlin-library", "Creates Kotlin library"],

    "pom":      ["pom", "Creates dependency managment sections"],

    "scala":    ["scala-application", "Scala application"],
    "scall":    ["scala-library", "Scala library"],

    "swifta":   ["swift-application", "Swift application"],
    "swiftl":   ["swift-library", "Swift library"]
}


HELP_MSG = f"""Java:
python3 {fname()} <option> project_name [args]

Other:
python3 {fname()} <option> project_name lang [args]
----------------------------------------------------------------------------------------------------------------------------
 <options>
Standard Java projets:
 --create-new,          -cp             - Creates new, simple project java project
 --create-advanced,     -cp             - Creates new gradle project
 --help,                -h              - Shows this help message

Standard other projects:
 --create-new-other,    -cpo            - Creates a project in specified language | Supported: (C/C++)

----------------------------------------------------------------------------------------------------------------------------
 [args]
Java:
 --main                                 - Creates new file with a main file
 --empty, -e, --none                    - Creates an empty project

Gradle:
 --all                                  - Creates a project with settings by default
 --type,    -t                          - Creates project with a specific type
 --dsl,     -d                          - Build script language
 --pkg ,    -p                          - Package name

C++:
 --lang, -l                             - Creates src file for C/C++ (c, c++)
 --include-cstd, -ics                   - Adds local useful standard library
 --make, -mk                            - Creates makefile with specific name for executable file name: --make target_name

Alowed types:"""


clangs = {
    0: "kotlin",
    1: "groovy"
}


#++++++ files ++++++
start_file = f"""#!/usr/bin/env bash
kitty --override initial_window_width=47c \
      --override initial_window_height=43c \
      >/dev/null 2>&1 &

disown
"""

java_std_file = """package main;
/*
    This code is generated by this program
*/
public class Main
{
    public static void main(String[] argv)
    {
        // Code
    }
}"""

java_std_comp_file = 



#++++++ functions +++++++
def version():
    v = f"""Java Ez by rNtR
Current version: {version_status}
"""
    return v


def simple_java_file() -> str:
    return java_std_file

