#!/bin/python3
import subprocess
import sys
import os


# globals
COMP_FILE_NAME = "build"
RIGHTS = "770" # rwx for user and group

MIN_ARGS = 2
MAX_ARGS = 4
alen = len(sys.argv)

STDO = "[\033[92m*\033[0m]: "
STDE = "[\033[91m!\033[0m]: "
STDI = "\033[92m>\033[0m "

opts = {
    "basic":    ["basic", "Creates empty gradle project"],
    
    "cppa":     ["cpp-application", "Creates C++ application"],
    "cppl":     ["cpp-library", "Creates C++ library"],
    
    "grva":     ["groovy-application", "Creates Groovy application"],
    "ggplug":   ["groovy-gradle-plugin", "Creates Groovy plugin"],
    
    "javaa":    ["java-application", "Creates Java application"],
    "javaplug": ["java-gradle-plugin", "Creates Java plugin"],
    "javal":    ["java-library", "Creates Java library"],

    "kota":     ["kotlin-application", "Creates Kotlin application",],
    "kotplug":  ["kotlin-gradle-plugin", "Creates Kotlin plugin"],
    "kotl":     ["kotlin-library", "Creates Kotlin library"],

    "pom":      ["pom", "Creates dependency managment sections"],

    "scala":    ["scala-application", "Scala application"],
    "scall":    ["scala-library", "Scala library"],

    "swifta":   ["swift-application", "Swift application"],
    "swiftl":   ["swift-library", "Swift library"]
}

clangs = {
    0: "kotlin",
    1: "groovy"
}

empty_java = """package main;
/*
    This code is generated by this program
*/
public class Main
{
    public static void main(String[] argv)
    {
        // Code
    }
}
"""


# functions
def fname() -> str:     return os.path.basename(__file__)


def comp_file(build_param:str) -> str:
    simple_comp_file = f"""#!/bin/bash
if [ "$#" -eq 0 ]; then
    javac -d out $(find src -name \"*.java\")
    {build_param}

else
    if [ $1 = "makepkg" ]; then
        mkdir "src/$2"
        echo "\033[92mPackage created!\033[0m"
    fi
fi
"""
    return simple_comp_file


clear = lambda: os.system("clear")


def help_msg() -> None:
    hmsg = f"""python3 {fname()} <options> project_name [args]
----------------------------------------------------------------------------------------------------------------------------
 <options>
Standard java projets:
 --create-new,          -cp             - creates new, simple project java project
 --create-advanced,     -cp             - creates new gradle project
 --help,                -h              - Shows this help message

Gradle projects:
 --all                                  - Creates a project with settings by default
 --type,    -t                          - Creates project with a specific type (application, basic, library, java-platform)
 --dsl,     -d                          - Build script language
 --pkg ,    -p                          - Package name

----------------------------------------------------------------------------------------------------------------------------
 [args]
 --main                                 - Creates new file with a main file
 --empty, -e, --none                    - Creates an empty project

Alowed types:"""  
    print(hmsg)

    for a, b in opts.items():
        print(f" - {a}  \t\t\t\t- {b[1]}")

    print("----------------------------------------------------------------------------------------------------------------------------")


def create_simple_project(project_name:str, *args) -> None:
    print(f"{STDO}Creating project '{project_name}'...")
    try:
        subprocess.run(["mkdir", "-p", f"{project_name}/src"])
        subprocess.run(["mkdir", f"{project_name}/out"])
        build_param = ""
        for arg in args:
            if arg == "--main":
                subprocess.run(["mkdir", f"{project_name}/src/main"])
                with open(f"{project_name}/src/main/Main.java", "w") as jf:
                    jf.write(empty_java)
                    jf.close()
                build_param = "java -cp out main.Main"

            elif arg in ("--none", "-e", "--empty"):
                break

        # sh
        print(f"{STDO}Creating a new compiling file for project...")
        
        with open(f"{project_name}/{COMP_FILE_NAME}", "w") as f:
            f.write(comp_file(build_param))
            f.close()

        subprocess.run(["chmod", RIGHTS, f"{project_name}/{COMP_FILE_NAME}"])

    except Exception as e:
        print(f"{STDE}{e}")


def create_make_project(project_name:str, **kwargs) -> None:
    print(f"{STDO}Creating project '{project_name}'...")
    try:
        subprocess.run(["mkdir", "-p", f"{project_name}"])
        cmd = ["gradle", "init", "--project-dir", project_name]
        args = {}

        for arg, opt in kwargs.items():
            if arg in   ("--all"):
                args = { "--type": opts["javaa"], "--dsl": clangs[2], "--package": "main" }
                break 

            if arg in ("--type", "-t"):
                if opt not in list(opts.keys()):
                    print(f"{STDE}Bad type!")
                    return
               
                args["--type"] = opts[opt][0]


            if arg in ("--dsl", "-d"):
                if opt not in list(clangs.values()):
                    print(f"{STDE}Bad configuration language!")
                    return

                args["--dsl"]   = opt


            if arg in ("--pkg", "-p"):
                args["--package"]  = opt

        parms = [i for p in args.items() for i in p]
        #print(cmd + parms)
        subprocess.run(cmd + parms)

    except Exception as e:
        print(f"{STDE}{e}")


if __name__ == "__main__":
    if alen < MIN_ARGS: # or alen > MAX_ARGS):
        print(f"{STDE} Must be atleast 2 arguments!")
        sys.exit(1)

    if sys.argv[1] in ("--help", "-h"):
        help_msg()

    elif sys.argv[1] in ("--create-new", "-cp"):
        create_simple_project(sys.argv[2], sys.argv[3]) 
        print(f"{STDO}Done!")

    elif sys.argv[1] in ("--create-advanced", "-cap"):
        if alen % 2 == 0:
            print(f"{STDE}Missing parameter!")
            sys.exit(1)

        kwargs = {}
        
        if alen == 4:
            kwargs["--all"] = ""
            create_make_project(sys.argv[2], **kwargs)
            sys.exit(0)

        for i in range(alen):
            if i > 2 and i % 2 == 1:
                kwargs[sys.argv[i]] = sys.argv[i+1]
        
        create_make_project(sys.argv[2], **kwargs)

    else:
        print(f"{STDE} Something went wrong, try again!")

    sys.exit(0)

