#!/bin/python3
import subprocess
import sys
import os


# globals
version_status = "1.0.1"

COMP_FILE_NAME = "build"
START_FILE_NAME = "start"
RIGHTS = "770" # rwx for user and group

MIN_ARGS = 2
MAX_ARGS = 4
alen = len(sys.argv)

STDO = "[\033[92m*\033[0m]: "
STDE = "[\033[91m!\033[0m]: "
STDI = "\033[92m>\033[0m "

ROOT_PATH = "/usr/local/lib/javaz"

opts = {
    "basic":    ["basic", "Creates empty gradle project"],
    
    "cppa":     ["cpp-application", "Creates C++ application"],
    "cppl":     ["cpp-library", "Creates C++ library"],
    
    "grva":     ["groovy-application", "Creates Groovy application"],
    "ggplug":   ["groovy-gradle-plugin", "Creates Groovy plugin"],
    
    "javaa":    ["java-application", "Creates Java application"],
    "javaplug": ["java-gradle-plugin", "Creates Java plugin"],
    "javal":    ["java-library", "Creates Java library"],

    "kota":     ["kotlin-application", "Creates Kotlin application",],
    "kotplug":  ["kotlin-gradle-plugin", "Creates Kotlin plugin"],
    "kotl":     ["kotlin-library", "Creates Kotlin library"],

    "pom":      ["pom", "Creates dependency managment sections"],

    "scala":    ["scala-application", "Scala application"],
    "scall":    ["scala-library", "Scala library"],

    "swifta":   ["swift-application", "Swift application"],
    "swiftl":   ["swift-library", "Swift library"]
}

clangs = {
    0: "kotlin",
    1: "groovy"
}


# functions global
clear = lambda: os.system("clear")
def fname() -> str:     return os.path.basename(__file__)
def dict_to_list(d:dict) -> list:   return [i for p in d.items() for i in p]


def start_file(lang:str="java") -> str:
    open_vim = "./src/main/Main.java"

    if lang == "cpp":
        open_vim = "./main.cpp"
    
    sfile = f"""#!/usr/bin/env bash
kitty --override initial_window_width=47c \
      --override initial_window_height=43c \
      >/dev/null 2>&1 &

disown
nvim {open_vim} -c NERDTree"""
    return sfile


def remove_project(project_name:str) -> None:
    try:
        subprocess.run(["rm", "-rf", f"{project_name}/"])

    except Exception as e:
        print(f"{STDO}{e}")


def help_msg() -> None:
    hmsg = f"""Java:
python3 {fname()} <option> project_name [args]

Other:
python3 {fname()} <option> project_name lang [args]
----------------------------------------------------------------------------------------------------------------------------
 <options>
Standard Java projets:
 --create-new,          -cp             - Creates new, simple project java project
 --create-advanced,     -cp             - Creates new gradle project
 --help,                -h              - Shows this help message

Standard other projects:
 --create-new-other,    -cpo            - Creates a project in specified language | Supported: (C/C++)

----------------------------------------------------------------------------------------------------------------------------
 [args]
Java:
 --main                                 - Creates new file with a main file
 --empty, -e, --none                    - Creates an empty project

Gradle:
 --all                                  - Creates a project with settings by default
 --type,    -t                          - Creates project with a specific type
 --dsl,     -d                          - Build script language
 --pkg ,    -p                          - Package name

C++:
 --lang, -l                             - Creates src file for C/C++ (c, c++)
 --include-cstd, -ics                   - Adds local useful standard library
 --make, -mk                            - Creates makefile with specific name for executable file name: --make target_name

Alowed types:"""  
    print(hmsg)

    for a, b in opts.items():
        print(f" - {a}  \t\t\t\t- {b[1]}")

    #print("----------------------------------------------------------------------------------------------------------------------------")


def version():
    v = f"""Java Ez by rNtR
Current version: {version_status}
"""
    return v

#---------------------------------------------------------------------------------------
# java
def simple_java_file() -> str:
    java_file = """package main;
/*
    This code is generated by this program
*/
public class Main
{
    public static void main(String[] argv)
    {
        // Code
    }
}"""

    return java_file


def comp_file(build_param:str) -> str:
    simple_comp_file = f"""#!/bin/bash
if [ "$#" -eq 0 ]; then
    javac -d out $(find src -name \"*.java\")
    {build_param}

else
    if [ $1 = "makepkg" ]; then
        mkdir "src/$2"
        echo "\033[92mPackage created!\033[0m"
    fi
fi
"""
    return simple_comp_file


def create_simple_project(project_name:str, *args) -> None:
    print(f"{STDO}Creating project '{project_name}'...")
    try:
        subprocess.run(["mkdir", "-p", f"{project_name}/src"])
        subprocess.run(["mkdir", f"{project_name}/out"])
        build_param = ""
        for arg in args:
            if arg == "--main":
                subprocess.run(["mkdir", f"{project_name}/src/main"])
                with open(f"{project_name}/src/main/Main.java", "w") as jf:
                    jf.write(simple_java_file())
                    jf.close()
                build_param = "java -cp out main.Main"

            elif arg in ("--none", "-e", "--empty"):
                break

        # sh
        print(f"{STDO}Creating a new compiling file for project...")
        
        with open(f"{project_name}/{COMP_FILE_NAME}", "w") as f:
            f.write(comp_file(build_param))
            f.close()

        with open(f"{project_name}/{START_FILE_NAME}", "w") as sf:
            sf.write(start_file())
            sf.close()

        subprocess.run(["chmod", RIGHTS, f"{project_name}/{COMP_FILE_NAME}"])
        subprocess.run(["chmod", RIGHTS, f"{project_name}/{START_FILE_NAME}"])

    except Exception as e:
        print(f"{STDE}{e}")


def create_gradle_project(project_name:str, **kwargs) -> None:
    print(f"{STDO}Creating project '{project_name}'...")
    try:
        subprocess.run(["mkdir", "-p", f"{project_name}"])
        cmd = ["gradle", "init", "--project-dir", project_name]
        args = {}

        for arg, opt in kwargs.items():
            if arg in ("--all"):
                args = { "--type": opts["javaa"], "--dsl": clangs[2], "--package": "main" }
                break 

            if arg in ("--type", "-t"):
                if opt not in list(opts.keys()):
                    print(f"{STDE}Bad type!")
                    return
               
                args["--type"] = opts[opt][0]

            if arg in ("--dsl", "-d"):
                if opt not in list(clangs.values()):
                    print(f"{STDE}Bad configuration language!")
                    return

                args["--dsl"] = opt

            if arg in ("--pkg", "-p"):
                args["--package"] = opt

        parms = dict_to_list(args)
        
        with open(f"{project_name}/{START_FILE_NAME}", "w") as sf:
            sf.write(start_file())
            sf.close()

        subprocess.run(cmd + parms)

    except Exception as e:
        print(f"{STDE}{e}")

#-----------------------------------------------------------------------------------------------
# cpp
def make_file_contets(target:str, lang:str) -> str:
    comp = "g++"
    stdc = "c++20"
    fext = "cpp"

    if lang != "c++":
        comp = "gcc"
        stdc = "c17"
        fext = "c"

    simple_make_file = f"""CC={comp}
CCFLAGS=-std={stdc} -Wall -g
TARGET={target}
SRCS=main.{fext} $(wildcard lib/*.{fext})
OBJS=$(SRCS:.{fext}=.o)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CCFLAGS) $(OBJS) -o $(TARGET)

%.o: %.{fext}
	$(CC) $(CCFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)"""
    
    return simple_make_file


def simple_cpp_file(lang:str, author:str="rNtR", description:str="simple program") -> str:
    std_lib_to_inc = "iostream"
    if lang != "c++":
        std_lib_to_inc = "stdio.h"

    cpp_file = f"""/*
 * This {description} written by {author}
 * All rights reserved 2025 - ... ©
*/
#include <{std_lib_to_inc}>

int main(void)
{{
    // code

    return 0;
}}"""
    return cpp_file


def create_make_project(project_name:str, lang:str, *args) -> None:
    print(f"{STDO}Creating new project '{project_name}...'")
    try:
        subprocess.run(["mkdir", "-p", f"{project_name}/lib"]) 
       
        with open(f"{project_name}/main.{ 'cpp' if lang == 'c++' else 'c' }", "w") as cppf:
            cppf.write(simple_cpp_file(lang))
            cppf.close()

        with open(f"{project_name}/start", "w") as sf:
            sf.write(start_file("cpp"))
            sf.close()
        
        subprocess.run(["chmod", RIGHTS, f"{project_name}/start"])

        for arg in args:
            if not arg.startswith("-"):
                continue

            if arg in ("--include-cstd", "-ics"):
                cpp_lib = "libbsopen"
                print(f"{STDO}Adding Custom STD library...")
                subprocess.run(["cp", f"{ROOT_PATH}/std/{cpp_lib}.cpp", f"{project_name}/lib/"])
                subprocess.run(["cp", f"{ROOT_PATH}/std/{cpp_lib}.hpp", f"{project_name}/lib/"])

            if arg in ("--make", "-mk"):
                print(f"{STDO}Creating Makefile...")
                with open(f"{project_name}/Makefile", "w") as mf:
                    mf.write(make_file_contets(args[(args.index(arg))+1], lang))
                    mf.close()

    except Exception as e:
        print(f"{STDE}{e}")


if __name__ == "__main__":
    if alen < MIN_ARGS: # or alen > MAX_ARGS):
        print(f"{STDE} Must be atleast 2 arguments!")
        sys.exit(1)

    parms = []

    for a in sys.argv:
        if sys.argv.index(a) == 2:
            parms.append(a)
            continue

        parms.append(a.lower())

    #=============== Script ===============#
    if parms[1] in ("--help", "-h"):
        help_msg()

    elif parms[1] in ("--remove", "-rm"):
        prj_name = parms[2]
        print(f"{STDO}Removing project '{prj_name}'...".replace("/", ""))
        remove_project(prj_name)
        print(f"{STDO}Project '{prj_name}' successfully removed!".replace("/", ""))

    elif parms[1] in ("--version", "-v"):
        print(version())

    #=============== Java ===============#
    elif parms[1] in ("--create-new", "-cp"):
        create_simple_project(parms[2], parms[3]) 
        print(f"{STDO}Done!")

    elif parms[1] in ("--create-advanced", "-cap"):
        if alen % 2 == 0:
            print(f"{STDE}Missing parameter!")
            sys.exit(1)

        kwargs = {}
        
        if alen == 4:
            kwargs["--all"] = ""
            create_gradle_project(parms[2], **kwargs)
            sys.exit(0)

        for i in range(alen):
            if i > 2 and i % 2 == 1:
                kwargs[parms[i]] = parms[i+1]
        
        create_gradle_project(parms[2], **kwargs)

    #=============== CPP ===============#
    elif parms[1] in ("--create-new-other", "-cpo"):
        
        match parms[3]:
            case "c++" | "c":
                largs = []
                for parm in parms:
                    if parms.index(parm) > 3:
                        largs.append(parm)

                create_make_project(parms[2], parms[3], *largs)

            case _:
                print(f"{STDE}Language is not supported!")

    else:
        print(f"{STDE} Something went wrong, try again!")

    sys.exit(0)

